import type { DriverDashboardResponse } from '@/types/driver'
import type { TripListDto } from '@/types/trip'
import type { User } from '@/types/user'

export const STATIC_DRIVER_USER: User = {
  id: '00000000-0000-0000-0000-000000000099',
  email: 'driver.preview@fleetflow.local',
  phone_number: '+10000000000',
  first_name: 'Alex',
  last_name: 'Morgan',
  full_name: 'Alex Morgan',
  role: 'DRIVER',
  avatar: null,
  avatar_url: null,
  is_verified: true,
  is_active: true,
  date_joined: new Date().toISOString(),
  last_login: null,
  company_id: '00000000-0000-0000-0000-000000000001',
  company_name: 'Preview Logistics',
  has_company: true,
  driver_profile_id: '00000000-0000-0000-0000-000000000099',
}

export const STATIC_DRIVER_DASHBOARD: DriverDashboardResponse = {
  user: STATIC_DRIVER_USER,
  profile: {
    user: STATIC_DRIVER_USER,
    date_of_birth: '1990-05-12',
    address: '123 Preview Lane',
    emergency_contact_name: 'Jamie Morgan',
    emergency_contact_phone: '+10000000001',
    drivers_license_number: 'DL-PREVIEW-001',
    license_type: 'CLASS_B',
    license_expiry_date: '2027-06-01',
    license_issuing_country: 'US',
    employment_status: 'FULL_TIME',
    date_hired: '2024-01-15',
    employee_id: 'EMP-001',
    payment_rate: '45.00',
    payment_type: 'PER_TRIP',
    bank_account_number: null,
    bank_name: null,
    max_daily_hours: '12.0',
    max_weekly_hours: '60.0',
    total_trips: 42,
    completed_trips: 38,
    on_time_percentage: '94.50',
    average_rating: '4.80',
    is_active: true,
    is_available: true,
    is_license_expired: false,
    completion_rate: 90.5,
  },
  stats: {
    total_trips: 42,
    completed_trips: 38,
    completion_rate: 90.5,
    on_time_percentage: 94.5,
    average_rating: 4.8,
    pending_kyc_documents: 1,
  },
}

const now = new Date()
const today = now.toISOString()

export const STATIC_DRIVER_TRIPS: TripListDto[] = [
  {
    id: '10000000-0000-0000-0000-000000000001',
    trip_number: 'TRP-PREVIEW-001',
    status: 'ONGOING',
    pickup_location: 'Warehouse A, Industrial Park',
    destination: 'Retail Hub North',
    vehicle_registration: 'KDA 452X',
    driver: STATIC_DRIVER_USER.driver_profile_id!,
    driver_name: STATIC_DRIVER_USER.full_name,
    planned_departure_time: today,
    actual_departure_time: today,
    actual_arrival_time: null,
    updated_at: today,
    is_flagged: false,
    flag_reason: null,
    distance_km: 48,
    revenue_amount: null,
    fuel_cost: null,
    driver_payment: null,
    toll_cost: null,
    other_expenses: null,
    total_expenses: null,
    profit: null,
    created_at: today,
  },
  {
    id: '10000000-0000-0000-0000-000000000002',
    trip_number: 'TRP-PREVIEW-002',
    status: 'PLANNED',
    pickup_location: 'Depot 12',
    destination: 'Airport Cargo Terminal',
    vehicle_registration: 'KDA 452X',
    driver: STATIC_DRIVER_USER.driver_profile_id!,
    driver_name: STATIC_DRIVER_USER.full_name,
    planned_departure_time: today,
    actual_departure_time: null,
    actual_arrival_time: null,
    updated_at: today,
    is_flagged: false,
    flag_reason: null,
    distance_km: 22,
    revenue_amount: null,
    fuel_cost: null,
    driver_payment: null,
    toll_cost: null,
    other_expenses: null,
    total_expenses: null,
    profit: null,
    created_at: today,
  },
  {
    id: '10000000-0000-0000-0000-000000000003',
    trip_number: 'TRP-PREVIEW-003',
    status: 'COMPLETED',
    pickup_location: 'City Center',
    destination: 'Suburb West',
    vehicle_registration: 'KDA 452X',
    driver: STATIC_DRIVER_USER.driver_profile_id!,
    driver_name: STATIC_DRIVER_USER.full_name,
    planned_departure_time: today,
    actual_departure_time: today,
    actual_arrival_time: today,
    updated_at: today,
    is_flagged: false,
    flag_reason: null,
    distance_km: 31,
    revenue_amount: null,
    fuel_cost: null,
    driver_payment: null,
    toll_cost: null,
    other_expenses: null,
    total_expenses: null,
    profit: null,
    created_at: today,
  },
]
